{% if theme.passage_end_tag.enabled %}
<div style="text-align:center;color: #ccc;font-size:14px;">
------ 本文结束 ------</div>
<br/>
<div class="post-copy">
    <div style="margin-left:10px">
    <br/>
    <p style="font-size: 10px;line-height: 30px;">
        <a href="https://hylasborwen.github.io" ><i>Small Q~</i></a> by
        <a href="https://hylasborwen.github.io" >小祺。</a><br/>
        <span style="color:#F834FA">你说你不学习，你还能干嘛。</span>
    </p>
</div>
</div>
{% endif %}